language: node_js

node_js:
  - "10"

before_install:
  - npm install

script: npm run test

jobs:
  include:
    - stage: "Tests"
      name: "Stylelint"
      script: npm run stylelint
    - name: "Jest & SASS True"
      script: npm run jest
    - name: "Build"
      script: npm run build
